artifacts:
  artifacts_dir: artifacts
  trained_model_dir: model
  raw_local_dir: raw_local_dir
  raw_local_files: data.csv

  split_data_dir: split_data_dir
  train: train.csv
  test: test.csv
  model_dir: model_dir
  model_file: Elasticnet.model
  report_dir: report_dir
  report_file: Elasticnet.json

source_data:
  data_dir: data
  data_file: data.xml
