artifacts:
  artifacts_dir: artifacts
  prepared_data_dir: prepared
  train_data: train.csv
  test_data: test.csv
  feature_data_dir: feature
  feature_train_file: train.pkl
  feature_test_file: test.pkl

source_data:
  data_dir: data
  data_file: data.xml
