artifacts:
  artifacts_dir: artifacts
  prepared_data_dir: prepared
  train_data: train.csv
  test_data: test.csv
  split_data_dir: split_data_dir
  model_dir: model_dir
  model_file: Elasticnet.model
  report_dir: report_dir
  report_file: Elasticnet.json

source_data:
  data_dir: data
  data_file: data.xml
